## @file  azure-pipelines.yml
#
# Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
#  @par Specification Reference:
#  - https://aka.ms/yaml
#
##

trigger: none

pr:
- edk2-ci

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo Build Reason              = $(Build.Reason)
    echo Build Queued By           = $(Build.QueuedBy)
    echo Build Requested For Email = $(Build.RequestedForEmail)
    echo Build Requested For Id    = $(Build.RequestedForId)
    echo Build Source Branch       = $(Build.SourceBranch)
    set
    curl -i "https://api.github.com/user"
    curl -i "https://api.github.com/teams/1649488/members"
    curl -i "https://api.github.com/teams/1649488/memberships/mdkinney"
  displayName: 'Run a multi-line script'
